### PR TITLE
first commit

### PR DESCRIPTION
**Pull request by Fhayz**

### CODE REVIEW

**Comment by Fhayz** [comment]
I feel the left and right margins is too much sir

**Comment by Tosinuel** [comment]
Well done bro.
but you need to change your selector in CSS from tags/elements to class selectors: it's affecting other work done.
[remove h1, input, ul, li, etc and use classes instead]

**Comment by Fhayz** [comment]
Done

**Review by Tosinuel — CHANGES_REQUESTED** [review]
I want you to please check your work with what I have done before; your work scattered the existing work done.

Make sure when you're done, everything is intact.

**Comment by Tosinuel** [comment]
Job well done bro.
Bravo

**Pull request merged**
